// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:JuisCheck.JuisDeviceDialog.CmdQuery_Executed(System.Object,System.Windows.Input.ExecutedRoutedEventArgs)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:JuisCheck.DownloadDialog.WebClient_DownloadFileCompleted_Handler(System.Object,System.ComponentModel.AsyncCompletedEventArgs)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:JuisCheck.MainWindow.OpenDeviceCollection(System.String)")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:JuisCheck.MainWindow.SaveDeviceCollection~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:JuisCheck.MainWindow.SaveDeviceCollectionAs~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:JuisCheck.Program.Main")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:JuisCheck.JuisDevice.FindFirmwareUpdate(System.Windows.Threading.Dispatcher)~System.String")]
[assembly: SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:JuisCheck.XML.JC1Device.UpdateImageURL")]
[assembly: SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:JuisCheck.XML.JC1Device.UpdateInfoURL")]
[assembly: SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:JuisCheck.XML.JC2DectDevice.UpdateImageURL")]
[assembly: SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:JuisCheck.XML.JC2DectDevice.UpdateInfoURL")]
[assembly: SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:JuisCheck.XML.JC2JuisDevice.UpdateImageURL")]
[assembly: SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:JuisCheck.XML.JC2JuisDevice.UpdateInfoURL")]
[assembly: SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:JuisCheck.Device.UpdateImageURL")]
[assembly: SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:JuisCheck.Device.UpdateInfoURL")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~P:JuisCheck.MainWindow.Backstage_DefaultAnnexValues")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~P:JuisCheck.MainWindow.Backstage_DefaultBuildTypeValues")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~P:JuisCheck.MainWindow.Backstage_DefaultCountryValues")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~P:JuisCheck.MainWindow.Backstage_DefaultLanguageValues")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~P:JuisCheck.MainWindow.Backstage_DefaultOEMValues")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~P:JuisCheck.MainWindow.Backstage_UILanguageValues")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Backstage_CmdAbout")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Backstage_CmdClose")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Backstage_CmdExit")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Backstage_CmdOpen")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Backstage_CmdRecentFileOpen")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Backstage_CmdRecentFileRemove")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Backstage_CmdRecentFilesClean")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Backstage_CmdRecentFilesClear")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Backstage_CmdSave")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Backstage_CmdSaveAs")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Backstage_CmdSettingsDefault")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Devices_CmdAddDECT")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Devices_CmdAddJUIS")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Devices_CmdClearUpdates")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Devices_CmdCopy")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Devices_CmdCopyURLs")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Devices_CmdDelete")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Devices_CmdDownloadFirmware")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Devices_CmdEdit")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Devices_CmdFindUpdates")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Devices_CmdMakeCurrent")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Devices_CmdSelectAll")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Devices_CmdSelectNone")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~F:JuisCheck.MainWindow.Devices_CmdViewInfo")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~P:JuisCheck.MainWindow.Devices_ViewSource")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:JuisCheck.DeviceCollection.CollectionChanged_Handler(System.Object,System.Collections.Specialized.NotifyCollectionChangedEventArgs)")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:JuisCheck.DeviceCollection.Item_PropertyChanged_Handler(System.Object,System.ComponentModel.PropertyChangedEventArgs)")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:JuisCheck.DeviceCollection.Settings_PropertyChanged_Handler(System.Object,System.ComponentModel.PropertyChangedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE0016:Use 'throw' expression", Justification = "<Pending>", Scope = "member", Target = "~M:JuisCheck.CollectionSettings.Add(System.String,System.String)")]
