//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuisCheck.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JCstring {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JCstring() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JuisCheck.Lang.JCstring", typeof(JCstring).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string BackstageButtonTextAbout {
            get {
                return ResourceManager.GetString("BackstageButtonTextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string BackstageButtonTextClose {
            get {
                return ResourceManager.GetString("BackstageButtonTextClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string BackstageButtonTextExit {
            get {
                return ResourceManager.GetString("BackstageButtonTextExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string BackstageButtonTextOpen {
            get {
                return ResourceManager.GetString("BackstageButtonTextOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all files from list.
        /// </summary>
        public static string BackstageButtonTextRemoveAllFiles {
            get {
                return ResourceManager.GetString("BackstageButtonTextRemoveAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove non-existing files from list.
        /// </summary>
        public static string BackstageButtonTextRemoveNonExistingFiles {
            get {
                return ResourceManager.GetString("BackstageButtonTextRemoveNonExistingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to defaults.
        /// </summary>
        public static string BackstageButtonTextResetToDefaults {
            get {
                return ResourceManager.GetString("BackstageButtonTextResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BackstageButtonTextSave {
            get {
                return ResourceManager.GetString("BackstageButtonTextSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string BackstageButtonTextSaveAs {
            get {
                return ResourceManager.GetString("BackstageButtonTextSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display program information.
        /// </summary>
        public static string BackstageButtonTooltipAbout {
            get {
                return ResourceManager.GetString("BackstageButtonTooltipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the device collection [Ctrl+W].
        /// </summary>
        public static string BackstageButtonTooltipClose {
            get {
                return ResourceManager.GetString("BackstageButtonTooltipClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the program.
        /// </summary>
        public static string BackstageButtonTooltipExit {
            get {
                return ResourceManager.GetString("BackstageButtonTooltipExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a device collection from a file [Ctrl+O].
        /// </summary>
        public static string BackstageButtonTooltipOpen {
            get {
                return ResourceManager.GetString("BackstageButtonTooltipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the device collection to the file from which it was loaded [Ctrl+S].
        /// </summary>
        public static string BackstageButtonTooltipSave {
            get {
                return ResourceManager.GetString("BackstageButtonTooltipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the device collection to a different file [Ctrl+Alt+S].
        /// </summary>
        public static string BackstageButtonTooltipSaveAs {
            get {
                return ResourceManager.GetString("BackstageButtonTooltipSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string BackstageContextMenuItemTextOpen {
            get {
                return ResourceManager.GetString("BackstageContextMenuItemTextOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from list.
        /// </summary>
        public static string BackstageContextMenuItemTextRemove {
            get {
                return ResourceManager.GetString("BackstageContextMenuItemTextRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        public static string BackstageSectionHeaderDefaults {
            get {
                return ResourceManager.GetString("BackstageSectionHeaderDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string BackstageSectionHeaderGeneral {
            get {
                return ResourceManager.GetString("BackstageSectionHeaderGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent device collections.
        /// </summary>
        public static string BackstageSectionHeaderRecentFiles {
            get {
                return ResourceManager.GetString("BackstageSectionHeaderRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string BackstageTabTextRecent {
            get {
                return ResourceManager.GetString("BackstageTabTextRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string BackstageTabTextSettings {
            get {
                return ResourceManager.GetString("BackstageTabTextSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Recent Files panel.
        /// </summary>
        public static string BackstageTabTooltipRecent {
            get {
                return ResourceManager.GetString("BackstageTabTooltipRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Settings panel.
        /// </summary>
        public static string BackstageTabTooltipSettings {
            get {
                return ResourceManager.GetString("BackstageTabTooltipSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A (A).
        /// </summary>
        public static string ComboBoxValueAnnexA {
            get {
                return ResourceManager.GetString("ComboBoxValueAnnexA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B (B).
        /// </summary>
        public static string ComboBoxValueAnnexB {
            get {
                return ResourceManager.GetString("ComboBoxValueAnnexB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable (Kabel).
        /// </summary>
        public static string ComboBoxValueAnnexCable {
            get {
                return ResourceManager.GetString("ComboBoxValueAnnexCable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No annex (Ohne).
        /// </summary>
        public static string ComboBoxValueAnnexNone {
            get {
                return ResourceManager.GetString("ComboBoxValueAnnexNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inhouse beta (1000).
        /// </summary>
        public static string ComboBoxValueBuildtypeBetaInhouse {
            get {
                return ResourceManager.GetString("ComboBoxValueBuildtypeBetaInhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public beta (1001).
        /// </summary>
        public static string ComboBoxValueBuildtypeBetaPublic {
            get {
                return ResourceManager.GetString("ComboBoxValueBuildtypeBetaPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release (1).
        /// </summary>
        public static string ComboBoxValueBuildtypeRelease {
            get {
                return ResourceManager.GetString("ComboBoxValueBuildtypeRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigeria (0234).
        /// </summary>
        public static string ComboBoxValueCountry0234 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanzania (0255).
        /// </summary>
        public static string ComboBoxValueCountry0255 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uganda (0256).
        /// </summary>
        public static string ComboBoxValueCountry0256 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namibia (0264).
        /// </summary>
        public static string ComboBoxValueCountry0264 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Africa (027).
        /// </summary>
        public static string ComboBoxValueCountry027 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greece (030).
        /// </summary>
        public static string ComboBoxValueCountry030 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands (031).
        /// </summary>
        public static string ComboBoxValueCountry031 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium (032).
        /// </summary>
        public static string ComboBoxValueCountry032 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France (033).
        /// </summary>
        public static string ComboBoxValueCountry033 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain (034).
        /// </summary>
        public static string ComboBoxValueCountry034 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal (0351).
        /// </summary>
        public static string ComboBoxValueCountry0351 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0351", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg (0352).
        /// </summary>
        public static string ComboBoxValueCountry0352 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0352", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ireland (0353).
        /// </summary>
        public static string ComboBoxValueCountry0353 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0353", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyprus (0357).
        /// </summary>
        public static string ComboBoxValueCountry0357 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0357", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finland (0358).
        /// </summary>
        public static string ComboBoxValueCountry0358 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0358", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungary (036).
        /// </summary>
        public static string ComboBoxValueCountry036 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvia (0371).
        /// </summary>
        public static string ComboBoxValueCountry0371 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0371", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonia (0372).
        /// </summary>
        public static string ComboBoxValueCountry0372 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0372", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andorra (0376).
        /// </summary>
        public static string ComboBoxValueCountry0376 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0376", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montenegro (0382).
        /// </summary>
        public static string ComboBoxValueCountry0382 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0382", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatia (0385).
        /// </summary>
        public static string ComboBoxValueCountry0385 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0385", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenia (0386).
        /// </summary>
        public static string ComboBoxValueCountry0386 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0386", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnia and Herzegovina (0387).
        /// </summary>
        public static string ComboBoxValueCountry0387 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0387", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonia (0389).
        /// </summary>
        public static string ComboBoxValueCountry0389 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0389", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy (039).
        /// </summary>
        public static string ComboBoxValueCountry039 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland (041).
        /// </summary>
        public static string ComboBoxValueCountry041 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech Republic (0420).
        /// </summary>
        public static string ComboBoxValueCountry0420 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovakia (0421).
        /// </summary>
        public static string ComboBoxValueCountry0421 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austria (043).
        /// </summary>
        public static string ComboBoxValueCountry043 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom (044).
        /// </summary>
        public static string ComboBoxValueCountry044 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark (045).
        /// </summary>
        public static string ComboBoxValueCountry045 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden (046).
        /// </summary>
        public static string ComboBoxValueCountry046 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway (047).
        /// </summary>
        public static string ComboBoxValueCountry047 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland (048).
        /// </summary>
        public static string ComboBoxValueCountry048 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany (049).
        /// </summary>
        public static string ComboBoxValueCountry049 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina (054).
        /// </summary>
        public static string ComboBoxValueCountry054 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia (061).
        /// </summary>
        public static string ComboBoxValueCountry061 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand (064).
        /// </summary>
        public static string ComboBoxValueCountry064 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thailand (066).
        /// </summary>
        public static string ComboBoxValueCountry066 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israel (0972).
        /// </summary>
        public static string ComboBoxValueCountry0972 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry0972", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other country (99).
        /// </summary>
        public static string ComboBoxValueCountry99 {
            get {
                return ResourceManager.GetString("ComboBoxValueCountry99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (de).
        /// </summary>
        public static string ComboBoxValueLanguageDE {
            get {
                return ResourceManager.GetString("ComboBoxValueLanguageDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (en).
        /// </summary>
        public static string ComboBoxValueLanguageEN {
            get {
                return ResourceManager.GetString("ComboBoxValueLanguageEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (es).
        /// </summary>
        public static string ComboBoxValueLanguageES {
            get {
                return ResourceManager.GetString("ComboBoxValueLanguageES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French (fr).
        /// </summary>
        public static string ComboBoxValueLanguageFR {
            get {
                return ResourceManager.GetString("ComboBoxValueLanguageFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian (it).
        /// </summary>
        public static string ComboBoxValueLanguageIT {
            get {
                return ResourceManager.GetString("ComboBoxValueLanguageIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch (nl).
        /// </summary>
        public static string ComboBoxValueLanguageNL {
            get {
                return ResourceManager.GetString("ComboBoxValueLanguageNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish (pl).
        /// </summary>
        public static string ComboBoxValueLanguagePL {
            get {
                return ResourceManager.GetString("ComboBoxValueLanguagePL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not set).
        /// </summary>
        public static string ComboBoxValueNotSet {
            get {
                return ResourceManager.GetString("ComboBoxValueNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN ({0}).
        /// </summary>
        public static string ComboBoxValueUnknown {
            get {
                return ResourceManager.GetString("ComboBoxValueUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select columns.
        /// </summary>
        public static string ContextMenuTitleTextSelectColumns {
            get {
                return ResourceManager.GetString("ContextMenuTitleTextSelectColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Fritz!OS.
        /// </summary>
        public static string DataGridColumnHeaderBaseFritzOS {
            get {
                return ResourceManager.GetString("DataGridColumnHeaderBaseFritzOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string DataGridColumnHeaderCountry {
            get {
                return ResourceManager.GetString("DataGridColumnHeaderCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string DataGridColumnHeaderDeviceAddress {
            get {
                return ResourceManager.GetString("DataGridColumnHeaderDeviceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        public static string DataGridColumnHeaderDeviceName {
            get {
                return ResourceManager.GetString("DataGridColumnHeaderDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware.
        /// </summary>
        public static string DataGridColumnHeaderFirmware {
            get {
                return ResourceManager.GetString("DataGridColumnHeaderFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string DataGridColumnHeaderFirmwareBuildType {
            get {
                return ResourceManager.GetString("DataGridColumnHeaderFirmwareBuildType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HW.
        /// </summary>
        public static string DataGridColumnHeaderHardware {
            get {
                return ResourceManager.GetString("DataGridColumnHeaderHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lang.
        /// </summary>
        public static string DataGridColumnHeaderLanguage {
            get {
                return ResourceManager.GetString("DataGridColumnHeaderLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM.
        /// </summary>
        public static string DataGridColumnHeaderOEM {
            get {
                return ResourceManager.GetString("DataGridColumnHeaderOEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string DataGridColumnHeaderProductName {
            get {
                return ResourceManager.GetString("DataGridColumnHeaderProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update file name.
        /// </summary>
        public static string DataGridColumnHeaderUpdateFileName {
            get {
                return ResourceManager.GetString("DataGridColumnHeaderUpdateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string DataGridColumnHeaderUpdateInfo {
            get {
                return ResourceManager.GetString("DataGridColumnHeaderUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last checked.
        /// </summary>
        public static string DataGridColumnHeaderUpdateLastChecked {
            get {
                return ResourceManager.GetString("DataGridColumnHeaderUpdateLastChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annex.
        /// </summary>
        public static string DeviceFieldLabelAnnex {
            get {
                return ResourceManager.GetString("DeviceFieldLabelAnnex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Fritz!OS.
        /// </summary>
        public static string DeviceFieldLabelBaseFritzOS {
            get {
                return ResourceManager.GetString("DeviceFieldLabelBaseFritzOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string DeviceFieldLabelCountry {
            get {
                return ResourceManager.GetString("DeviceFieldLabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device address.
        /// </summary>
        public static string DeviceFieldLabelDeviceAddress {
            get {
                return ResourceManager.GetString("DeviceFieldLabelDeviceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        public static string DeviceFieldLabelDeviceName {
            get {
                return ResourceManager.GetString("DeviceFieldLabelDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware type.
        /// </summary>
        public static string DeviceFieldLabelFirmwareBuildType {
            get {
                return ResourceManager.GetString("DeviceFieldLabelFirmwareBuildType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware version.
        /// </summary>
        public static string DeviceFieldLabelFirmwareVersion {
            get {
                return ResourceManager.GetString("DeviceFieldLabelFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string DeviceFieldLabelFlags {
            get {
                return ResourceManager.GetString("DeviceFieldLabelFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware type.
        /// </summary>
        public static string DeviceFieldLabelHardwareType {
            get {
                return ResourceManager.GetString("DeviceFieldLabelHardwareType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string DeviceFieldLabelLanguage {
            get {
                return ResourceManager.GetString("DeviceFieldLabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last checked.
        /// </summary>
        public static string DeviceFieldLabelLastChecked {
            get {
                return ResourceManager.GetString("DeviceFieldLabelLastChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM.
        /// </summary>
        public static string DeviceFieldLabelOEM {
            get {
                return ResourceManager.GetString("DeviceFieldLabelOEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string DeviceFieldLabelProductName {
            get {
                return ResourceManager.GetString("DeviceFieldLabelProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        public static string DeviceFieldLabelSerialNumber {
            get {
                return ResourceManager.GetString("DeviceFieldLabelSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update file name.
        /// </summary>
        public static string DeviceFieldLabelUpdateFileName {
            get {
                return ResourceManager.GetString("DeviceFieldLabelUpdateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update info.
        /// </summary>
        public static string DeviceFieldLabelUpdateInfo {
            get {
                return ResourceManager.GetString("DeviceFieldLabelUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unusual firmware major version (should be hardware type - 72).
        /// </summary>
        public static string DeviceTooltipUnusualFirmwareMajorWarning {
            get {
                return ResourceManager.GetString("DeviceTooltipUnusualFirmwareMajorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DialogButtonTextCancel {
            get {
                return ResourceManager.GetString("DialogButtonTextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DialogButtonTextOk {
            get {
                return ResourceManager.GetString("DialogButtonTextOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string DialogButtonTextQuery {
            get {
                return ResourceManager.GetString("DialogButtonTextQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device properties.
        /// </summary>
        public static string DialogCaptionDeviceProperties {
            get {
                return ResourceManager.GetString("DialogCaptionDeviceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find updates.
        /// </summary>
        public static string DialogCaptionFindUpdates {
            get {
                return ResourceManager.GetString("DialogCaptionFindUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string DialogCaptionOpen {
            get {
                return ResourceManager.GetString("DialogCaptionOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string DialogCaptionSave {
            get {
                return ResourceManager.GetString("DialogCaptionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string FileNameNew {
            get {
                return ResourceManager.GetString("FileNameNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MessageCaptionAbout {
            get {
                return ResourceManager.GetString("MessageCaptionAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MessageCaptionDelete {
            get {
                return ResourceManager.GetString("MessageCaptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageCaptionError {
            get {
                return ResourceManager.GetString("MessageCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error.
        /// </summary>
        public static string MessageCaptionFatalError {
            get {
                return ResourceManager.GetString("MessageCaptionFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved data.
        /// </summary>
        public static string MessageCaptionUnsavedData {
            get {
                return ResourceManager.GetString("MessageCaptionUnsavedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JuisCheck for Windows v{0}\n\nCopyright (C) 2018 Roger Hünen.
        /// </summary>
        public static string MessageTextAbout {
            get {
                return ResourceManager.GetString("MessageTextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data could not be copied to the clipboard.\nThe clipboard may be locked by another program..
        /// </summary>
        public static string MessageTextClipboardCopyFailure {
            get {
                return ResourceManager.GetString("MessageTextClipboardCopyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} selected devices?.
        /// </summary>
        public static string MessageTextDeleteMultipleDevices {
            get {
                return ResourceManager.GetString("MessageTextDeleteMultipleDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete 1 selected device?.
        /// </summary>
        public static string MessageTextDeleteOneDevice {
            get {
                return ResourceManager.GetString("MessageTextDeleteOneDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get data from device.\n\n{0}.
        /// </summary>
        public static string MessageTextDeviceQueryFailed {
            get {
                return ResourceManager.GetString("MessageTextDeviceQueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid firmware update version.\n\nDevice: {0}\nVersion: {1}.
        /// </summary>
        public static string MessageTextInvalidUpdateVersion {
            get {
                return ResourceManager.GetString("MessageTextInvalidUpdateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device collection could not be loaded.\n\n{0}.
        /// </summary>
        public static string MessageTextOpenDeviceCollectionFailed {
            get {
                return ResourceManager.GetString("MessageTextOpenDeviceCollectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device collection could not be saved.\n\n{0}.
        /// </summary>
        public static string MessageTextSaveDeviceCollectionFailed {
            get {
                return ResourceManager.GetString("MessageTextSaveDeviceCollectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception: {0}\n\nException information could not be copied to the clipboard..
        /// </summary>
        public static string MessageTextUnhandledExceptionCopyFailure {
            get {
                return ResourceManager.GetString("MessageTextUnhandledExceptionCopyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception: {0}\n\nException information has been copied to the clipboard..
        /// </summary>
        public static string MessageTextUnhandledExceptionCopySuccess {
            get {
                return ResourceManager.GetString("MessageTextUnhandledExceptionCopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data is modified. Changes will be\nlost if you do not save the data.\n\nSave the data now?.
        /// </summary>
        public static string MessageTextUnsavedData {
            get {
                return ResourceManager.GetString("MessageTextUnsavedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JuisCheck for Windows.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add DECT.
        /// </summary>
        public static string RibbonButtonTextAddDECT {
            get {
                return ResourceManager.GetString("RibbonButtonTextAddDECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Device.
        /// </summary>
        public static string RibbonButtonTextAddJUIS {
            get {
                return ResourceManager.GetString("RibbonButtonTextAddJUIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Updates.
        /// </summary>
        public static string RibbonButtonTextClearUpdates {
            get {
                return ResourceManager.GetString("RibbonButtonTextClearUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy URLs.
        /// </summary>
        public static string RibbonButtonTextCopyURLs {
            get {
                return ResourceManager.GetString("RibbonButtonTextCopyURLs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string RibbonButtonTextDelete {
            get {
                return ResourceManager.GetString("RibbonButtonTextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string RibbonButtonTextEdit {
            get {
                return ResourceManager.GetString("RibbonButtonTextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Updates.
        /// </summary>
        public static string RibbonButtonTextFindUpdates {
            get {
                return ResourceManager.GetString("RibbonButtonTextFindUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Image.
        /// </summary>
        public static string RibbonButtonTextGetImage {
            get {
                return ResourceManager.GetString("RibbonButtonTextGetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Current.
        /// </summary>
        public static string RibbonButtonTextMakeCurrent {
            get {
                return ResourceManager.GetString("RibbonButtonTextMakeCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string RibbonButtonTextSelectAll {
            get {
                return ResourceManager.GetString("RibbonButtonTextSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        public static string RibbonButtonTextSelectNone {
            get {
                return ResourceManager.GetString("RibbonButtonTextSelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Info.
        /// </summary>
        public static string RibbonButtonTextViewInfo {
            get {
                return ResourceManager.GetString("RibbonButtonTextViewInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new device to the list (FRITZ!DECT).
        /// </summary>
        public static string RibbonButtonTooltipAddDECT {
            get {
                return ResourceManager.GetString("RibbonButtonTooltipAddDECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new device to the list (FRITZ!Box, FRITZ!Powerline, FRITZ!WLAN).
        /// </summary>
        public static string RibbonButtonTooltipAddJUIS {
            get {
                return ResourceManager.GetString("RibbonButtonTooltipAddJUIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the update information for the selected devices.
        /// </summary>
        public static string RibbonButtonTooltipClearUpdates {
            get {
                return ResourceManager.GetString("RibbonButtonTooltipClearUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the image download URLs of the selected devices to the clipboard.
        /// </summary>
        public static string RibbonButtonTooltipCopyURLs {
            get {
                return ResourceManager.GetString("RibbonButtonTooltipCopyURLs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected devices from the device collection.
        /// </summary>
        public static string RibbonButtonTooltipDelete {
            get {
                return ResourceManager.GetString("RibbonButtonTooltipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the selected device.
        /// </summary>
        public static string RibbonButtonTooltipEdit {
            get {
                return ResourceManager.GetString("RibbonButtonTooltipEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query the AVM update service to find new firmware for the selected devices.
        /// </summary>
        public static string RibbonButtonTooltipFindUpdates {
            get {
                return ResourceManager.GetString("RibbonButtonTooltipFindUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch the default browser to get the firmware image for the selected device.
        /// </summary>
        public static string RibbonButtonTooltipGetImage {
            get {
                return ResourceManager.GetString("RibbonButtonTooltipGetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the latest firmware the current firmware for the selected devices.
        /// </summary>
        public static string RibbonButtonTooltipMakeCurrent {
            get {
                return ResourceManager.GetString("RibbonButtonTooltipMakeCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all devices.
        /// </summary>
        public static string RibbonButtonTooltipSelectAll {
            get {
                return ResourceManager.GetString("RibbonButtonTooltipSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select no device.
        /// </summary>
        public static string RibbonButtonTooltipSelectNone {
            get {
                return ResourceManager.GetString("RibbonButtonTooltipSelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch the default browser to view the firmware release notes for the selected device.
        /// </summary>
        public static string RibbonButtonTooltipViewInfo {
            get {
                return ResourceManager.GetString("RibbonButtonTooltipViewInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string RibbonGroupBoxTextDevices {
            get {
                return ResourceManager.GetString("RibbonGroupBoxTextDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Update.
        /// </summary>
        public static string RibbonGroupBoxTextFirmwareUpdate {
            get {
                return ResourceManager.GetString("RibbonGroupBoxTextFirmwareUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string RibbonTabHeaderDevices {
            get {
                return ResourceManager.GetString("RibbonTabHeaderDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string RribbontabHeaderFile {
            get {
                return ResourceManager.GetString("RribbontabHeaderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically load the current device collection at next program start.
        /// </summary>
        public static string SettingLabelAutoLoad {
            get {
                return ResourceManager.GetString("SettingLabelAutoLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annex.
        /// </summary>
        public static string SettingLabelDefaultAnnex {
            get {
                return ResourceManager.GetString("SettingLabelDefaultAnnex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECT base Fritz!OS.
        /// </summary>
        public static string SettingLabelDefaultBaseFritzOS {
            get {
                return ResourceManager.GetString("SettingLabelDefaultBaseFritzOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string SettingLabelDefaultCountry {
            get {
                return ResourceManager.GetString("SettingLabelDefaultCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware type.
        /// </summary>
        public static string SettingLabelDefaultFirmwareBuildType {
            get {
                return ResourceManager.GetString("SettingLabelDefaultFirmwareBuildType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingLabelDefaultLanguage {
            get {
                return ResourceManager.GetString("SettingLabelDefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM.
        /// </summary>
        public static string SettingLabelDefaultOEM {
            get {
                return ResourceManager.GetString("SettingLabelDefaultOEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show build number for release versions (if available).
        /// </summary>
        public static string SettingLabelJuisReleaseShowBuildNumber {
            get {
                return ResourceManager.GetString("SettingLabelJuisReleaseShowBuildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore window size and position on startup.
        /// </summary>
        public static string SettingLabelMainWindowRestoreMetrics {
            get {
                return ResourceManager.GetString("SettingLabelMainWindowRestoreMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of recent files.
        /// </summary>
        public static string SettingLabelRecentFilesMax {
            get {
                return ResourceManager.GetString("SettingLabelRecentFilesMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string UpdateInfoError {
            get {
                return ResourceManager.GetString("UpdateInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string UpdateInfoNone {
            get {
                return ResourceManager.GetString("UpdateInfoNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UpdateInfoUnknown {
            get {
                return ResourceManager.GetString("UpdateInfoUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input is empty or white space.
        /// </summary>
        public static string ValidationErrorEmptyOrWhiteSpace {
            get {
                return ResourceManager.GetString("ValidationErrorEmptyOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input contains invalid characters.
        /// </summary>
        public static string ValidationErrorInvalidCharacters {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Fritz!OS version format is invalid (example: 113.07.01).
        /// </summary>
        public static string ValidationErrorInvalidFritzOSversion {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidFritzOSversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value selected.
        /// </summary>
        public static string ValidationErrorNoValueSelected {
            get {
                return ResourceManager.GetString("ValidationErrorNoValueSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input is out of range ({0}-{1}).
        /// </summary>
        public static string ValidationErrorValueOutOfRange {
            get {
                return ResourceManager.GetString("ValidationErrorValueOutOfRange", resourceCulture);
            }
        }
    }
}
