//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuisCheck.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JCstring {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JCstring() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JuisCheck.Lang.JCstring", typeof(JCstring).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string backstageButtonTextAbout {
            get {
                return ResourceManager.GetString("backstageButtonTextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string backstageButtonTextClose {
            get {
                return ResourceManager.GetString("backstageButtonTextClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string backstageButtonTextExit {
            get {
                return ResourceManager.GetString("backstageButtonTextExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string backstageButtonTextOpen {
            get {
                return ResourceManager.GetString("backstageButtonTextOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove non-existing files from list.
        /// </summary>
        public static string backstageButtonTextRemoveNonExistingFiles {
            get {
                return ResourceManager.GetString("backstageButtonTextRemoveNonExistingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string backstageButtonTextSave {
            get {
                return ResourceManager.GetString("backstageButtonTextSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string backstageButtonTextSaveAs {
            get {
                return ResourceManager.GetString("backstageButtonTextSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display program information.
        /// </summary>
        public static string backstageButtonTooltipAbout {
            get {
                return ResourceManager.GetString("backstageButtonTooltipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the device collection [Ctrl+W].
        /// </summary>
        public static string backstageButtonTooltipClose {
            get {
                return ResourceManager.GetString("backstageButtonTooltipClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the program.
        /// </summary>
        public static string backstageButtonTooltipExit {
            get {
                return ResourceManager.GetString("backstageButtonTooltipExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a device collection from a file [Ctrl+O].
        /// </summary>
        public static string backstageButtonTooltipOpen {
            get {
                return ResourceManager.GetString("backstageButtonTooltipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the device collection to the file from which it was loaded [Ctrl+S].
        /// </summary>
        public static string backstageButtonTooltipSave {
            get {
                return ResourceManager.GetString("backstageButtonTooltipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the device collection to a different file [Ctrl+Alt+S].
        /// </summary>
        public static string backstageButtonTooltipSaveAs {
            get {
                return ResourceManager.GetString("backstageButtonTooltipSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string backstageContextMenuItemTextOpen {
            get {
                return ResourceManager.GetString("backstageContextMenuItemTextOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from list.
        /// </summary>
        public static string backstageContextMenuItemTextRemove {
            get {
                return ResourceManager.GetString("backstageContextMenuItemTextRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        public static string backstageSectionHeaderDefaults {
            get {
                return ResourceManager.GetString("backstageSectionHeaderDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string backstageSectionHeaderGeneral {
            get {
                return ResourceManager.GetString("backstageSectionHeaderGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUIS devices.
        /// </summary>
        public static string backstageSectionHeaderJuisDevices {
            get {
                return ResourceManager.GetString("backstageSectionHeaderJuisDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent device collections.
        /// </summary>
        public static string backstageSectionHeaderRecentFiles {
            get {
                return ResourceManager.GetString("backstageSectionHeaderRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string backstageTabTextRecent {
            get {
                return ResourceManager.GetString("backstageTabTextRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string backstageTabTextSettings {
            get {
                return ResourceManager.GetString("backstageTabTextSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Recent Files panel.
        /// </summary>
        public static string backstageTabTooltipRecent {
            get {
                return ResourceManager.GetString("backstageTabTooltipRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Settings panel.
        /// </summary>
        public static string backstageTabTooltipSettings {
            get {
                return ResourceManager.GetString("backstageTabTooltipSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A (A).
        /// </summary>
        public static string comboboxValueAnnexA {
            get {
                return ResourceManager.GetString("comboboxValueAnnexA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B (B).
        /// </summary>
        public static string comboboxValueAnnexB {
            get {
                return ResourceManager.GetString("comboboxValueAnnexB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable (Kabel).
        /// </summary>
        public static string comboboxValueAnnexCable {
            get {
                return ResourceManager.GetString("comboboxValueAnnexCable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No annex (Ohne).
        /// </summary>
        public static string comboboxValueAnnexNone {
            get {
                return ResourceManager.GetString("comboboxValueAnnexNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inhouse beta (1000).
        /// </summary>
        public static string comboboxValueBuildtypeBetaInhouse {
            get {
                return ResourceManager.GetString("comboboxValueBuildtypeBetaInhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public beta (1001).
        /// </summary>
        public static string comboboxValueBuildtypeBetaPublic {
            get {
                return ResourceManager.GetString("comboboxValueBuildtypeBetaPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release (1).
        /// </summary>
        public static string comboboxValueBuildtypeRelease {
            get {
                return ResourceManager.GetString("comboboxValueBuildtypeRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigeria (0234).
        /// </summary>
        public static string comboboxValueCountry0234 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanzania (0255).
        /// </summary>
        public static string comboboxValueCountry0255 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uganda (0256).
        /// </summary>
        public static string comboboxValueCountry0256 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namibia (0264).
        /// </summary>
        public static string comboboxValueCountry0264 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Africa (027).
        /// </summary>
        public static string comboboxValueCountry027 {
            get {
                return ResourceManager.GetString("comboboxValueCountry027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greece (030).
        /// </summary>
        public static string comboboxValueCountry030 {
            get {
                return ResourceManager.GetString("comboboxValueCountry030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netherlands (031).
        /// </summary>
        public static string comboboxValueCountry031 {
            get {
                return ResourceManager.GetString("comboboxValueCountry031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium (032).
        /// </summary>
        public static string comboboxValueCountry032 {
            get {
                return ResourceManager.GetString("comboboxValueCountry032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France (033).
        /// </summary>
        public static string comboboxValueCountry033 {
            get {
                return ResourceManager.GetString("comboboxValueCountry033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain (034).
        /// </summary>
        public static string comboboxValueCountry034 {
            get {
                return ResourceManager.GetString("comboboxValueCountry034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugal (0351).
        /// </summary>
        public static string comboboxValueCountry0351 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0351", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxembourg (0352).
        /// </summary>
        public static string comboboxValueCountry0352 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0352", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ireland (0353).
        /// </summary>
        public static string comboboxValueCountry0353 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0353", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyprus (0357).
        /// </summary>
        public static string comboboxValueCountry0357 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0357", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finland (0358).
        /// </summary>
        public static string comboboxValueCountry0358 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0358", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungary (036).
        /// </summary>
        public static string comboboxValueCountry036 {
            get {
                return ResourceManager.GetString("comboboxValueCountry036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvia (0371).
        /// </summary>
        public static string comboboxValueCountry0371 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0371", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonia (0372).
        /// </summary>
        public static string comboboxValueCountry0372 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0372", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andorra (0376).
        /// </summary>
        public static string comboboxValueCountry0376 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0376", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montenegro (0382).
        /// </summary>
        public static string comboboxValueCountry0382 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0382", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatia (0385).
        /// </summary>
        public static string comboboxValueCountry0385 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0385", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenia (0386).
        /// </summary>
        public static string comboboxValueCountry0386 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0386", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosnia and Herzegovina (0387).
        /// </summary>
        public static string comboboxValueCountry0387 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0387", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonia (0389).
        /// </summary>
        public static string comboboxValueCountry0389 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0389", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy (039).
        /// </summary>
        public static string comboboxValueCountry039 {
            get {
                return ResourceManager.GetString("comboboxValueCountry039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland (041).
        /// </summary>
        public static string comboboxValueCountry041 {
            get {
                return ResourceManager.GetString("comboboxValueCountry041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech Republic (0420).
        /// </summary>
        public static string comboboxValueCountry0420 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovakia (0421).
        /// </summary>
        public static string comboboxValueCountry0421 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austria (043).
        /// </summary>
        public static string comboboxValueCountry043 {
            get {
                return ResourceManager.GetString("comboboxValueCountry043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom (044).
        /// </summary>
        public static string comboboxValueCountry044 {
            get {
                return ResourceManager.GetString("comboboxValueCountry044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark (045).
        /// </summary>
        public static string comboboxValueCountry045 {
            get {
                return ResourceManager.GetString("comboboxValueCountry045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden (046).
        /// </summary>
        public static string comboboxValueCountry046 {
            get {
                return ResourceManager.GetString("comboboxValueCountry046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway (047).
        /// </summary>
        public static string comboboxValueCountry047 {
            get {
                return ResourceManager.GetString("comboboxValueCountry047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland (048).
        /// </summary>
        public static string comboboxValueCountry048 {
            get {
                return ResourceManager.GetString("comboboxValueCountry048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany (049).
        /// </summary>
        public static string comboboxValueCountry049 {
            get {
                return ResourceManager.GetString("comboboxValueCountry049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina (054).
        /// </summary>
        public static string comboboxValueCountry054 {
            get {
                return ResourceManager.GetString("comboboxValueCountry054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia (061).
        /// </summary>
        public static string comboboxValueCountry061 {
            get {
                return ResourceManager.GetString("comboboxValueCountry061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand (064).
        /// </summary>
        public static string comboboxValueCountry064 {
            get {
                return ResourceManager.GetString("comboboxValueCountry064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thailand (066).
        /// </summary>
        public static string comboboxValueCountry066 {
            get {
                return ResourceManager.GetString("comboboxValueCountry066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israel (0972).
        /// </summary>
        public static string comboboxValueCountry0972 {
            get {
                return ResourceManager.GetString("comboboxValueCountry0972", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other country (99).
        /// </summary>
        public static string comboboxValueCountry99 {
            get {
                return ResourceManager.GetString("comboboxValueCountry99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (de).
        /// </summary>
        public static string comboboxValueLanguageDE {
            get {
                return ResourceManager.GetString("comboboxValueLanguageDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (en).
        /// </summary>
        public static string comboboxValueLanguageEN {
            get {
                return ResourceManager.GetString("comboboxValueLanguageEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (es).
        /// </summary>
        public static string comboboxValueLanguageES {
            get {
                return ResourceManager.GetString("comboboxValueLanguageES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French (fr).
        /// </summary>
        public static string comboboxValueLanguageFR {
            get {
                return ResourceManager.GetString("comboboxValueLanguageFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian (it).
        /// </summary>
        public static string comboboxValueLanguageIT {
            get {
                return ResourceManager.GetString("comboboxValueLanguageIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch (nl).
        /// </summary>
        public static string comboboxValueLanguageNL {
            get {
                return ResourceManager.GetString("comboboxValueLanguageNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish (pl).
        /// </summary>
        public static string comboboxValueLanguagePL {
            get {
                return ResourceManager.GetString("comboboxValueLanguagePL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not set).
        /// </summary>
        public static string comboboxValueNotSet {
            get {
                return ResourceManager.GetString("comboboxValueNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN ({0}).
        /// </summary>
        public static string comboboxValueUnknown {
            get {
                return ResourceManager.GetString("comboboxValueUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Fritz!OS.
        /// </summary>
        public static string datagridColumnHeaderBaseFritzOS {
            get {
                return ResourceManager.GetString("datagridColumnHeaderBaseFritzOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string datagridColumnHeaderDeviceAddress {
            get {
                return ResourceManager.GetString("datagridColumnHeaderDeviceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        public static string datagridColumnHeaderDeviceName {
            get {
                return ResourceManager.GetString("datagridColumnHeaderDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware.
        /// </summary>
        public static string datagridColumnHeaderFirmware {
            get {
                return ResourceManager.GetString("datagridColumnHeaderFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string datagridColumnHeaderFirmwareBuildType {
            get {
                return ResourceManager.GetString("datagridColumnHeaderFirmwareBuildType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last checked.
        /// </summary>
        public static string datagridColumnHeaderLastChecked {
            get {
                return ResourceManager.GetString("datagridColumnHeaderLastChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM.
        /// </summary>
        public static string datagridColumnHeaderOem {
            get {
                return ResourceManager.GetString("datagridColumnHeaderOem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string datagridColumnHeaderProductName {
            get {
                return ResourceManager.GetString("datagridColumnHeaderProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string datagridColumnHeaderUpdate {
            get {
                return ResourceManager.GetString("datagridColumnHeaderUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annex.
        /// </summary>
        public static string deviceFieldLabelAnnex {
            get {
                return ResourceManager.GetString("deviceFieldLabelAnnex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Fritz!OS.
        /// </summary>
        public static string deviceFieldLabelBaseFritzOS {
            get {
                return ResourceManager.GetString("deviceFieldLabelBaseFritzOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string deviceFieldLabelCountry {
            get {
                return ResourceManager.GetString("deviceFieldLabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device address.
        /// </summary>
        public static string deviceFieldLabelDeviceAddress {
            get {
                return ResourceManager.GetString("deviceFieldLabelDeviceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        public static string deviceFieldLabelDeviceName {
            get {
                return ResourceManager.GetString("deviceFieldLabelDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware type.
        /// </summary>
        public static string deviceFieldLabelFirmwareBuildType {
            get {
                return ResourceManager.GetString("deviceFieldLabelFirmwareBuildType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware version.
        /// </summary>
        public static string deviceFieldLabelFirmwareVersion {
            get {
                return ResourceManager.GetString("deviceFieldLabelFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string deviceFieldLabelFlags {
            get {
                return ResourceManager.GetString("deviceFieldLabelFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware type.
        /// </summary>
        public static string deviceFieldLabelHardwareType {
            get {
                return ResourceManager.GetString("deviceFieldLabelHardwareType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string deviceFieldLabelLanguage {
            get {
                return ResourceManager.GetString("deviceFieldLabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last checked.
        /// </summary>
        public static string deviceFieldLabelLastChecked {
            get {
                return ResourceManager.GetString("deviceFieldLabelLastChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM.
        /// </summary>
        public static string deviceFieldLabelOem {
            get {
                return ResourceManager.GetString("deviceFieldLabelOem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string deviceFieldLabelProductName {
            get {
                return ResourceManager.GetString("deviceFieldLabelProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        public static string deviceFieldLabelSerialNumber {
            get {
                return ResourceManager.GetString("deviceFieldLabelSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update file name.
        /// </summary>
        public static string deviceFieldLabelUpdateFileName {
            get {
                return ResourceManager.GetString("deviceFieldLabelUpdateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update info.
        /// </summary>
        public static string deviceFieldLabelUpdateInfo {
            get {
                return ResourceManager.GetString("deviceFieldLabelUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unusual firmware major version (should be hardware type - 72).
        /// </summary>
        public static string deviceTooltipUnusualFirmwareMajorWarning {
            get {
                return ResourceManager.GetString("deviceTooltipUnusualFirmwareMajorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string dialogButtonTextCancel {
            get {
                return ResourceManager.GetString("dialogButtonTextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string dialogButtonTextOk {
            get {
                return ResourceManager.GetString("dialogButtonTextOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string dialogButtonTextQuery {
            get {
                return ResourceManager.GetString("dialogButtonTextQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device properties.
        /// </summary>
        public static string dialogCaptionDeviceProperties {
            get {
                return ResourceManager.GetString("dialogCaptionDeviceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find updates.
        /// </summary>
        public static string dialogCaptionFindUpdates {
            get {
                return ResourceManager.GetString("dialogCaptionFindUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string dialogCaptionOpen {
            get {
                return ResourceManager.GetString("dialogCaptionOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string dialogCaptionSave {
            get {
                return ResourceManager.GetString("dialogCaptionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string fileNameNew {
            get {
                return ResourceManager.GetString("fileNameNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string messageCaptionAbout {
            get {
                return ResourceManager.GetString("messageCaptionAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string messageCaptionDelete {
            get {
                return ResourceManager.GetString("messageCaptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string messageCaptionError {
            get {
                return ResourceManager.GetString("messageCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error.
        /// </summary>
        public static string messageCaptionFatalError {
            get {
                return ResourceManager.GetString("messageCaptionFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved data.
        /// </summary>
        public static string messageCaptionUnsavedData {
            get {
                return ResourceManager.GetString("messageCaptionUnsavedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JuisCheck for Windows\n\nCopyright (C) 2018 Roger Hünen.
        /// </summary>
        public static string messageTextAbout {
            get {
                return ResourceManager.GetString("messageTextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data could not be copied to the clipboard.\nThe clipboard may be locked by another program..
        /// </summary>
        public static string messageTextClipboardCopyFailure {
            get {
                return ResourceManager.GetString("messageTextClipboardCopyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} selected devices?.
        /// </summary>
        public static string messageTextDeleteMultipleDevices {
            get {
                return ResourceManager.GetString("messageTextDeleteMultipleDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete 1 selected device?.
        /// </summary>
        public static string messageTextDeleteOneDevice {
            get {
                return ResourceManager.GetString("messageTextDeleteOneDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get data from device.\n\n{0}.
        /// </summary>
        public static string messageTextDeviceQueryFailed {
            get {
                return ResourceManager.GetString("messageTextDeviceQueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid firmware update version.\n\nDevice: {0}\nVersion: {1}.
        /// </summary>
        public static string messageTextInvalidUpdateVersion {
            get {
                return ResourceManager.GetString("messageTextInvalidUpdateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device collection could not be loaded.\n\n{0}.
        /// </summary>
        public static string messageTextOpenDeviceCollectionFailed {
            get {
                return ResourceManager.GetString("messageTextOpenDeviceCollectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device collection could not be saved.\n\n{0}.
        /// </summary>
        public static string messageTextSaveDeviceCollectionFailed {
            get {
                return ResourceManager.GetString("messageTextSaveDeviceCollectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception: {0}\n\nException information could not be copied to the clipboard..
        /// </summary>
        public static string messageTextUnhandledExceptionCopyFailure {
            get {
                return ResourceManager.GetString("messageTextUnhandledExceptionCopyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception: {0}\n\nException information has been copied to the clipboard..
        /// </summary>
        public static string messageTextUnhandledExceptionCopySuccess {
            get {
                return ResourceManager.GetString("messageTextUnhandledExceptionCopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data is modified. Changes will be\nlost if you do not save the data.\n\nSave the data now?.
        /// </summary>
        public static string messageTextUnsavedData {
            get {
                return ResourceManager.GetString("messageTextUnsavedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JuisCheck for Windows.
        /// </summary>
        public static string programName {
            get {
                return ResourceManager.GetString("programName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add DECT.
        /// </summary>
        public static string ribbonButtonTextAddDECT {
            get {
                return ResourceManager.GetString("ribbonButtonTextAddDECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Device.
        /// </summary>
        public static string ribbonButtonTextAddJUIS {
            get {
                return ResourceManager.GetString("ribbonButtonTextAddJUIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Updates.
        /// </summary>
        public static string ribbonButtonTextClearUpdates {
            get {
                return ResourceManager.GetString("ribbonButtonTextClearUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy URLs.
        /// </summary>
        public static string ribbonButtonTextCopyURLs {
            get {
                return ResourceManager.GetString("ribbonButtonTextCopyURLs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ribbonButtonTextDelete {
            get {
                return ResourceManager.GetString("ribbonButtonTextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ribbonButtonTextEdit {
            get {
                return ResourceManager.GetString("ribbonButtonTextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Updates.
        /// </summary>
        public static string ribbonButtonTextFindUpdates {
            get {
                return ResourceManager.GetString("ribbonButtonTextFindUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Image.
        /// </summary>
        public static string ribbonButtonTextGetImage {
            get {
                return ResourceManager.GetString("ribbonButtonTextGetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Current.
        /// </summary>
        public static string ribbonButtonTextMakeCurrent {
            get {
                return ResourceManager.GetString("ribbonButtonTextMakeCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string ribbonButtonTextSelectAll {
            get {
                return ResourceManager.GetString("ribbonButtonTextSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        public static string ribbonButtonTextSelectNone {
            get {
                return ResourceManager.GetString("ribbonButtonTextSelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Info.
        /// </summary>
        public static string ribbonButtonTextViewInfo {
            get {
                return ResourceManager.GetString("ribbonButtonTextViewInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new device to the list (FRITZ!DECT).
        /// </summary>
        public static string ribbonButtonTooltipAddDECT {
            get {
                return ResourceManager.GetString("ribbonButtonTooltipAddDECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new device to the list (FRITZ!Box, FRITZ!Powerline, FRITZ!WLAN).
        /// </summary>
        public static string ribbonButtonTooltipAddJUIS {
            get {
                return ResourceManager.GetString("ribbonButtonTooltipAddJUIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the update information for the selected devices.
        /// </summary>
        public static string ribbonButtonTooltipClearUpdates {
            get {
                return ResourceManager.GetString("ribbonButtonTooltipClearUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the image download URLs of the selected devices to the clipboard.
        /// </summary>
        public static string ribbonButtonTooltipCopyURLs {
            get {
                return ResourceManager.GetString("ribbonButtonTooltipCopyURLs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected devices from the device collection.
        /// </summary>
        public static string ribbonButtonTooltipDelete {
            get {
                return ResourceManager.GetString("ribbonButtonTooltipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the selected device.
        /// </summary>
        public static string ribbonButtonTooltipEdit {
            get {
                return ResourceManager.GetString("ribbonButtonTooltipEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query the AVM update service to find new firmware for the selected devices.
        /// </summary>
        public static string ribbonButtonTooltipFindUpdates {
            get {
                return ResourceManager.GetString("ribbonButtonTooltipFindUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch the default browser to get the firmware image for the selected device.
        /// </summary>
        public static string ribbonButtonTooltipGetImage {
            get {
                return ResourceManager.GetString("ribbonButtonTooltipGetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the latest firmware the current firmware for the selected devices.
        /// </summary>
        public static string ribbonButtonTooltipMakeCurrent {
            get {
                return ResourceManager.GetString("ribbonButtonTooltipMakeCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all devices.
        /// </summary>
        public static string ribbonButtonTooltipSelectAll {
            get {
                return ResourceManager.GetString("ribbonButtonTooltipSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select no device.
        /// </summary>
        public static string ribbonButtonTooltipSelectNone {
            get {
                return ResourceManager.GetString("ribbonButtonTooltipSelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch the default browser to view the firmware release notes for the selected device.
        /// </summary>
        public static string ribbonButtonTooltipViewInfo {
            get {
                return ResourceManager.GetString("ribbonButtonTooltipViewInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string ribbonGroupBoxTextDevices {
            get {
                return ResourceManager.GetString("ribbonGroupBoxTextDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Update.
        /// </summary>
        public static string ribbonGroupBoxTextFirmwareUpdate {
            get {
                return ResourceManager.GetString("ribbonGroupBoxTextFirmwareUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string ribbonTabHeaderDevices {
            get {
                return ResourceManager.GetString("ribbonTabHeaderDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ribbontabHeaderFile {
            get {
                return ResourceManager.GetString("ribbontabHeaderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annex.
        /// </summary>
        public static string settingLabelDefaultAnnex {
            get {
                return ResourceManager.GetString("settingLabelDefaultAnnex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECT base Fritz!OS.
        /// </summary>
        public static string settingLabelDefaultBaseFritzOS {
            get {
                return ResourceManager.GetString("settingLabelDefaultBaseFritzOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string settingLabelDefaultCountry {
            get {
                return ResourceManager.GetString("settingLabelDefaultCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware type.
        /// </summary>
        public static string settingLabelDefaultFirmwareBuildType {
            get {
                return ResourceManager.GetString("settingLabelDefaultFirmwareBuildType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string settingLabelDefaultLanguage {
            get {
                return ResourceManager.GetString("settingLabelDefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM.
        /// </summary>
        public static string settingLabelDefaultOEM {
            get {
                return ResourceManager.GetString("settingLabelDefaultOEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show build number for release versions (if available).
        /// </summary>
        public static string settingLabelJuisReleaseShowBuildNumber {
            get {
                return ResourceManager.GetString("settingLabelJuisReleaseShowBuildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore window size and position on startup.
        /// </summary>
        public static string settingLabelMainWindowRestoreMetrics {
            get {
                return ResourceManager.GetString("settingLabelMainWindowRestoreMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of recent files.
        /// </summary>
        public static string settingLabelRecentFilesMax {
            get {
                return ResourceManager.GetString("settingLabelRecentFilesMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string updateInfoError {
            get {
                return ResourceManager.GetString("updateInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string updateInfoNone {
            get {
                return ResourceManager.GetString("updateInfoNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string updateInfoUnknown {
            get {
                return ResourceManager.GetString("updateInfoUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input is empty or white space.
        /// </summary>
        public static string validationErrorEmptyOrWhiteSpace {
            get {
                return ResourceManager.GetString("validationErrorEmptyOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input contains invalid characters.
        /// </summary>
        public static string validationErrorInvalidCharacters {
            get {
                return ResourceManager.GetString("validationErrorInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Fritz!OS version format is invalid (example: 113.07.01).
        /// </summary>
        public static string validationErrorInvalidFritzOSversion {
            get {
                return ResourceManager.GetString("validationErrorInvalidFritzOSversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value selected.
        /// </summary>
        public static string validationErrorNoValueSelected {
            get {
                return ResourceManager.GetString("validationErrorNoValueSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input is out of range ({0}-{1}).
        /// </summary>
        public static string validationErrorValueOutOfRange {
            get {
                return ResourceManager.GetString("validationErrorValueOutOfRange", resourceCulture);
            }
        }
    }
}
