//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 
namespace AVM.JUIS {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="JUISSoapBinding", Namespace="http://juis.avm.de/updateinfo")]
    public partial class JUIS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BoxFirmwareDowngradeCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback SoftwareUpdateCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback BoxFirmwareUpdateCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeviceFirmwareUpdateCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback BPjMUpdateCheckOperationCompleted;
        
        /// <remarks/>
        public JUIS() {
            this.Url = "https://jws.avm.de:443/Jason/UpdateInfoService";
        }
        
        /// <remarks/>
        public event BoxFirmwareDowngradeCheckCompletedEventHandler BoxFirmwareDowngradeCheckCompleted;
        
        /// <remarks/>
        public event SoftwareUpdateCheckCompletedEventHandler SoftwareUpdateCheckCompleted;
        
        /// <remarks/>
        public event BoxFirmwareUpdateCheckCompletedEventHandler BoxFirmwareUpdateCheckCompleted;
        
        /// <remarks/>
        public event DeviceFirmwareUpdateCheckCompletedEventHandler DeviceFirmwareUpdateCheckCompleted;
        
        /// <remarks/>
        public event BPjMUpdateCheckCompletedEventHandler BPjMUpdateCheckCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://juis.avm.de/updateinfo", ResponseNamespace="http://juis.avm.de/updateinfo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseUpdateInfo")]
        public ResponseUpdateInfo BoxFirmwareDowngradeCheck(RequestHeader RequestHeader, BoxInfo BoxInfo) {
            object[] results = this.Invoke("BoxFirmwareDowngradeCheck", new object[] {
                        RequestHeader,
                        BoxInfo});
            return ((ResponseUpdateInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBoxFirmwareDowngradeCheck(RequestHeader RequestHeader, BoxInfo BoxInfo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BoxFirmwareDowngradeCheck", new object[] {
                        RequestHeader,
                        BoxInfo}, callback, asyncState);
        }
        
        /// <remarks/>
        public ResponseUpdateInfo EndBoxFirmwareDowngradeCheck(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ResponseUpdateInfo)(results[0]));
        }
        
        /// <remarks/>
        public void BoxFirmwareDowngradeCheckAsync(RequestHeader RequestHeader, BoxInfo BoxInfo) {
            this.BoxFirmwareDowngradeCheckAsync(RequestHeader, BoxInfo, null);
        }
        
        /// <remarks/>
        public void BoxFirmwareDowngradeCheckAsync(RequestHeader RequestHeader, BoxInfo BoxInfo, object userState) {
            if ((this.BoxFirmwareDowngradeCheckOperationCompleted == null)) {
                this.BoxFirmwareDowngradeCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBoxFirmwareDowngradeCheckOperationCompleted);
            }
            this.InvokeAsync("BoxFirmwareDowngradeCheck", new object[] {
                        RequestHeader,
                        BoxInfo}, this.BoxFirmwareDowngradeCheckOperationCompleted, userState);
        }
        
        private void OnBoxFirmwareDowngradeCheckOperationCompleted(object arg) {
            if ((this.BoxFirmwareDowngradeCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BoxFirmwareDowngradeCheckCompleted(this, new BoxFirmwareDowngradeCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://juis.avm.de/updateinfo", ResponseNamespace="http://juis.avm.de/updateinfo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseUpdateInfo")]
        public ResponseUpdateInfo SoftwareUpdateCheck(RequestHeader RequestHeader, SoftwareInfo SoftwareInfo) {
            object[] results = this.Invoke("SoftwareUpdateCheck", new object[] {
                        RequestHeader,
                        SoftwareInfo});
            return ((ResponseUpdateInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSoftwareUpdateCheck(RequestHeader RequestHeader, SoftwareInfo SoftwareInfo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SoftwareUpdateCheck", new object[] {
                        RequestHeader,
                        SoftwareInfo}, callback, asyncState);
        }
        
        /// <remarks/>
        public ResponseUpdateInfo EndSoftwareUpdateCheck(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ResponseUpdateInfo)(results[0]));
        }
        
        /// <remarks/>
        public void SoftwareUpdateCheckAsync(RequestHeader RequestHeader, SoftwareInfo SoftwareInfo) {
            this.SoftwareUpdateCheckAsync(RequestHeader, SoftwareInfo, null);
        }
        
        /// <remarks/>
        public void SoftwareUpdateCheckAsync(RequestHeader RequestHeader, SoftwareInfo SoftwareInfo, object userState) {
            if ((this.SoftwareUpdateCheckOperationCompleted == null)) {
                this.SoftwareUpdateCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSoftwareUpdateCheckOperationCompleted);
            }
            this.InvokeAsync("SoftwareUpdateCheck", new object[] {
                        RequestHeader,
                        SoftwareInfo}, this.SoftwareUpdateCheckOperationCompleted, userState);
        }
        
        private void OnSoftwareUpdateCheckOperationCompleted(object arg) {
            if ((this.SoftwareUpdateCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SoftwareUpdateCheckCompleted(this, new SoftwareUpdateCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://juis.avm.de/updateinfo", ResponseNamespace="http://juis.avm.de/updateinfo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseUpdateInfo")]
        public ResponseUpdateInfo BoxFirmwareUpdateCheck(RequestHeader RequestHeader, BoxInfo BoxInfo, BoxInfo BoxInfoMeshMaster) {
            object[] results = this.Invoke("BoxFirmwareUpdateCheck", new object[] {
                        RequestHeader,
                        BoxInfo,
                        BoxInfoMeshMaster});
            return ((ResponseUpdateInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBoxFirmwareUpdateCheck(RequestHeader RequestHeader, BoxInfo BoxInfo, BoxInfo BoxInfoMeshMaster, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BoxFirmwareUpdateCheck", new object[] {
                        RequestHeader,
                        BoxInfo,
                        BoxInfoMeshMaster}, callback, asyncState);
        }
        
        /// <remarks/>
        public ResponseUpdateInfo EndBoxFirmwareUpdateCheck(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ResponseUpdateInfo)(results[0]));
        }
        
        /// <remarks/>
        public void BoxFirmwareUpdateCheckAsync(RequestHeader RequestHeader, BoxInfo BoxInfo, BoxInfo BoxInfoMeshMaster) {
            this.BoxFirmwareUpdateCheckAsync(RequestHeader, BoxInfo, BoxInfoMeshMaster, null);
        }
        
        /// <remarks/>
        public void BoxFirmwareUpdateCheckAsync(RequestHeader RequestHeader, BoxInfo BoxInfo, BoxInfo BoxInfoMeshMaster, object userState) {
            if ((this.BoxFirmwareUpdateCheckOperationCompleted == null)) {
                this.BoxFirmwareUpdateCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBoxFirmwareUpdateCheckOperationCompleted);
            }
            this.InvokeAsync("BoxFirmwareUpdateCheck", new object[] {
                        RequestHeader,
                        BoxInfo,
                        BoxInfoMeshMaster}, this.BoxFirmwareUpdateCheckOperationCompleted, userState);
        }
        
        private void OnBoxFirmwareUpdateCheckOperationCompleted(object arg) {
            if ((this.BoxFirmwareUpdateCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BoxFirmwareUpdateCheckCompleted(this, new BoxFirmwareUpdateCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://juis.avm.de/updateinfo", ResponseNamespace="http://juis.avm.de/updateinfo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseUpdateInfo")]
        public ResponseUpdateInfo DeviceFirmwareUpdateCheck(RequestHeader RequestHeader, BoxInfo BoxInfo, DeviceInfo DeviceInfo) {
            object[] results = this.Invoke("DeviceFirmwareUpdateCheck", new object[] {
                        RequestHeader,
                        BoxInfo,
                        DeviceInfo});
            return ((ResponseUpdateInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeviceFirmwareUpdateCheck(RequestHeader RequestHeader, BoxInfo BoxInfo, DeviceInfo DeviceInfo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeviceFirmwareUpdateCheck", new object[] {
                        RequestHeader,
                        BoxInfo,
                        DeviceInfo}, callback, asyncState);
        }
        
        /// <remarks/>
        public ResponseUpdateInfo EndDeviceFirmwareUpdateCheck(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ResponseUpdateInfo)(results[0]));
        }
        
        /// <remarks/>
        public void DeviceFirmwareUpdateCheckAsync(RequestHeader RequestHeader, BoxInfo BoxInfo, DeviceInfo DeviceInfo) {
            this.DeviceFirmwareUpdateCheckAsync(RequestHeader, BoxInfo, DeviceInfo, null);
        }
        
        /// <remarks/>
        public void DeviceFirmwareUpdateCheckAsync(RequestHeader RequestHeader, BoxInfo BoxInfo, DeviceInfo DeviceInfo, object userState) {
            if ((this.DeviceFirmwareUpdateCheckOperationCompleted == null)) {
                this.DeviceFirmwareUpdateCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeviceFirmwareUpdateCheckOperationCompleted);
            }
            this.InvokeAsync("DeviceFirmwareUpdateCheck", new object[] {
                        RequestHeader,
                        BoxInfo,
                        DeviceInfo}, this.DeviceFirmwareUpdateCheckOperationCompleted, userState);
        }
        
        private void OnDeviceFirmwareUpdateCheckOperationCompleted(object arg) {
            if ((this.DeviceFirmwareUpdateCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeviceFirmwareUpdateCheckCompleted(this, new DeviceFirmwareUpdateCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://juis.avm.de/updateinfo", ResponseNamespace="http://juis.avm.de/updateinfo", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ResponseUpdateInfo")]
        public ResponseUpdateInfo BPjMUpdateCheck(RequestHeader RequestHeader, BoxInfo BoxInfo, string BPjMVersion) {
            object[] results = this.Invoke("BPjMUpdateCheck", new object[] {
                        RequestHeader,
                        BoxInfo,
                        BPjMVersion});
            return ((ResponseUpdateInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBPjMUpdateCheck(RequestHeader RequestHeader, BoxInfo BoxInfo, string BPjMVersion, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BPjMUpdateCheck", new object[] {
                        RequestHeader,
                        BoxInfo,
                        BPjMVersion}, callback, asyncState);
        }
        
        /// <remarks/>
        public ResponseUpdateInfo EndBPjMUpdateCheck(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ResponseUpdateInfo)(results[0]));
        }
        
        /// <remarks/>
        public void BPjMUpdateCheckAsync(RequestHeader RequestHeader, BoxInfo BoxInfo, string BPjMVersion) {
            this.BPjMUpdateCheckAsync(RequestHeader, BoxInfo, BPjMVersion, null);
        }
        
        /// <remarks/>
        public void BPjMUpdateCheckAsync(RequestHeader RequestHeader, BoxInfo BoxInfo, string BPjMVersion, object userState) {
            if ((this.BPjMUpdateCheckOperationCompleted == null)) {
                this.BPjMUpdateCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBPjMUpdateCheckOperationCompleted);
            }
            this.InvokeAsync("BPjMUpdateCheck", new object[] {
                        RequestHeader,
                        BoxInfo,
                        BPjMVersion}, this.BPjMUpdateCheckOperationCompleted, userState);
        }
        
        private void OnBPjMUpdateCheckOperationCompleted(object arg) {
            if ((this.BPjMUpdateCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BPjMUpdateCheckCompleted(this, new BPjMUpdateCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://juis.avm.de/request")]
    public partial class RequestHeader {
        
        private string nonceField;
        
        private string userAgentField;
        
        private bool manualRequestField;
        
        /// <remarks/>
        public string Nonce {
            get {
                return this.nonceField;
            }
            set {
                this.nonceField = value;
            }
        }
        
        /// <remarks/>
        public string UserAgent {
            get {
                return this.userAgentField;
            }
            set {
                this.userAgentField = value;
            }
        }
        
        /// <remarks/>
        public bool ManualRequest {
            get {
                return this.manualRequestField;
            }
            set {
                this.manualRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://juis.avm.de/request")]
    public partial class DeviceInfo {
        
        private int typeField;
        
        private int hwField;
        
        private bool hwFieldSpecified;
        
        private string mHWField;
        
        private string versionField;
        
        private string serialField;
        
        private string langField;
        
        /// <remarks/>
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public int HW {
            get {
                return this.hwField;
            }
            set {
                this.hwField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HWSpecified {
            get {
                return this.hwFieldSpecified;
            }
            set {
                this.hwFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string MHW {
            get {
                return this.mHWField;
            }
            set {
                this.mHWField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
            }
        }
        
        /// <remarks/>
        public string Lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://juis.avm.de/request")]
    public partial class SoftwareInfo {
        
        private string nameField;
        
        private string versionField;
        
        private string langField;
        
        private string osField;
        
        private string serialField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string Lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        public string OS {
            get {
                return this.osField;
            }
            set {
                this.osField = value;
            }
        }
        
        /// <remarks/>
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://juis.avm.de/response")]
    public partial class UpdateInfo {
        
        private int checkIntervalField;
        
        private bool foundField;
        
        private string nameField;
        
        private string versionField;
        
        private int typeField;
        
        private bool typeFieldSpecified;
        
        private string downloadURLField;
        
        private string infoURLField;
        
        private string infoTextField;
        
        private string hintURLField;
        
        private string iconURLField;
        
        private int priorityField;
        
        private bool priorityFieldSpecified;
        
        private int autoUpdateStartTimeField;
        
        private int autoUpdateEndTimeField;
        
        private bool autoUpdateKeepServicesField;
        
        /// <remarks/>
        public int CheckInterval {
            get {
                return this.checkIntervalField;
            }
            set {
                this.checkIntervalField = value;
            }
        }
        
        /// <remarks/>
        public bool Found {
            get {
                return this.foundField;
            }
            set {
                this.foundField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string DownloadURL {
            get {
                return this.downloadURLField;
            }
            set {
                this.downloadURLField = value;
            }
        }
        
        /// <remarks/>
        public string InfoURL {
            get {
                return this.infoURLField;
            }
            set {
                this.infoURLField = value;
            }
        }
        
        /// <remarks/>
        public string InfoText {
            get {
                return this.infoTextField;
            }
            set {
                this.infoTextField = value;
            }
        }
        
        /// <remarks/>
        public string HintURL {
            get {
                return this.hintURLField;
            }
            set {
                this.hintURLField = value;
            }
        }
        
        /// <remarks/>
        public string IconURL {
            get {
                return this.iconURLField;
            }
            set {
                this.iconURLField = value;
            }
        }
        
        /// <remarks/>
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int AutoUpdateStartTime {
            get {
                return this.autoUpdateStartTimeField;
            }
            set {
                this.autoUpdateStartTimeField = value;
            }
        }
        
        /// <remarks/>
        public int AutoUpdateEndTime {
            get {
                return this.autoUpdateEndTimeField;
            }
            set {
                this.autoUpdateEndTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool AutoUpdateKeepServices {
            get {
                return this.autoUpdateKeepServicesField;
            }
            set {
                this.autoUpdateKeepServicesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://juis.avm.de/response")]
    public partial class ResponseHeader {
        
        private string nonceField;
        
        /// <remarks/>
        public string Nonce {
            get {
                return this.nonceField;
            }
            set {
                this.nonceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://juis.avm.de/response")]
    public partial class ResponseUpdateInfo {
        
        private ResponseHeader responseHeaderField;
        
        private UpdateInfo updateInfoField;
        
        /// <remarks/>
        public ResponseHeader ResponseHeader {
            get {
                return this.responseHeaderField;
            }
            set {
                this.responseHeaderField = value;
            }
        }
        
        /// <remarks/>
        public UpdateInfo UpdateInfo {
            get {
                return this.updateInfoField;
            }
            set {
                this.updateInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://juis.avm.de/request")]
    public partial class BoxInfo {
        
        private string nameField;
        
        private int hwField;
        
        private int majorField;
        
        private int minorField;
        
        private int patchField;
        
        private int buildnumberField;
        
        private int buildtypeField;
        
        private string serialField;
        
        private string oEMField;
        
        private string langField;
        
        private string countryField;
        
        private string annexField;
        
        private string[] flagField;
        
        private int updateConfigField;
        
        private string providerField;
        
        private string providerNameField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int HW {
            get {
                return this.hwField;
            }
            set {
                this.hwField = value;
            }
        }
        
        /// <remarks/>
        public int Major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
            }
        }
        
        /// <remarks/>
        public int Minor {
            get {
                return this.minorField;
            }
            set {
                this.minorField = value;
            }
        }
        
        /// <remarks/>
        public int Patch {
            get {
                return this.patchField;
            }
            set {
                this.patchField = value;
            }
        }
        
        /// <remarks/>
        public int Buildnumber {
            get {
                return this.buildnumberField;
            }
            set {
                this.buildnumberField = value;
            }
        }
        
        /// <remarks/>
        public int Buildtype {
            get {
                return this.buildtypeField;
            }
            set {
                this.buildtypeField = value;
            }
        }
        
        /// <remarks/>
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
            }
        }
        
        /// <remarks/>
        public string OEM {
            get {
                return this.oEMField;
            }
            set {
                this.oEMField = value;
            }
        }
        
        /// <remarks/>
        public string Lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Annex {
            get {
                return this.annexField;
            }
            set {
                this.annexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Flag")]
        public string[] Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
            }
        }
        
        /// <remarks/>
        public int UpdateConfig {
            get {
                return this.updateConfigField;
            }
            set {
                this.updateConfigField = value;
            }
        }
        
        /// <remarks/>
        public string Provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
            }
        }
        
        /// <remarks/>
        public string ProviderName {
            get {
                return this.providerNameField;
            }
            set {
                this.providerNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void BoxFirmwareDowngradeCheckCompletedEventHandler(object sender, BoxFirmwareDowngradeCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BoxFirmwareDowngradeCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BoxFirmwareDowngradeCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseUpdateInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseUpdateInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void SoftwareUpdateCheckCompletedEventHandler(object sender, SoftwareUpdateCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SoftwareUpdateCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SoftwareUpdateCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseUpdateInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseUpdateInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void BoxFirmwareUpdateCheckCompletedEventHandler(object sender, BoxFirmwareUpdateCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BoxFirmwareUpdateCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BoxFirmwareUpdateCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseUpdateInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseUpdateInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void DeviceFirmwareUpdateCheckCompletedEventHandler(object sender, DeviceFirmwareUpdateCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeviceFirmwareUpdateCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeviceFirmwareUpdateCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseUpdateInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseUpdateInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void BPjMUpdateCheckCompletedEventHandler(object sender, BPjMUpdateCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BPjMUpdateCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BPjMUpdateCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseUpdateInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseUpdateInfo)(this.results[0]));
            }
        }
    }
}
