//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuisCheck.JUIS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://juis.avm.de/updateinfo")]
    public partial class JuisSoapExceptionBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://juis.avm.de/response")]
    public partial class UpdateInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int checkIntervalField;
        
        private bool foundField;
        
        private string nameField;
        
        private string versionField;
        
        private int typeField;
        
        private bool typeFieldSpecified;
        
        private string downloadURLField;
        
        private string infoURLField;
        
        private string infoTextField;
        
        private string hintURLField;
        
        private string iconURLField;
        
        private int priorityField;
        
        private bool priorityFieldSpecified;
        
        private int autoUpdateStartTimeField;
        
        private int autoUpdateEndTimeField;
        
        private bool autoUpdateKeepServicesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CheckInterval {
            get {
                return this.checkIntervalField;
            }
            set {
                this.checkIntervalField = value;
                this.RaisePropertyChanged("CheckInterval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Found {
            get {
                return this.foundField;
            }
            set {
                this.foundField = value;
                this.RaisePropertyChanged("Found");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("TypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DownloadURL {
            get {
                return this.downloadURLField;
            }
            set {
                this.downloadURLField = value;
                this.RaisePropertyChanged("DownloadURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string InfoURL {
            get {
                return this.infoURLField;
            }
            set {
                this.infoURLField = value;
                this.RaisePropertyChanged("InfoURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string InfoText {
            get {
                return this.infoTextField;
            }
            set {
                this.infoTextField = value;
                this.RaisePropertyChanged("InfoText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string HintURL {
            get {
                return this.hintURLField;
            }
            set {
                this.hintURLField = value;
                this.RaisePropertyChanged("HintURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string IconURL {
            get {
                return this.iconURLField;
            }
            set {
                this.iconURLField = value;
                this.RaisePropertyChanged("IconURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
                this.RaisePropertyChanged("PrioritySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int AutoUpdateStartTime {
            get {
                return this.autoUpdateStartTimeField;
            }
            set {
                this.autoUpdateStartTimeField = value;
                this.RaisePropertyChanged("AutoUpdateStartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int AutoUpdateEndTime {
            get {
                return this.autoUpdateEndTimeField;
            }
            set {
                this.autoUpdateEndTimeField = value;
                this.RaisePropertyChanged("AutoUpdateEndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool AutoUpdateKeepServices {
            get {
                return this.autoUpdateKeepServicesField;
            }
            set {
                this.autoUpdateKeepServicesField = value;
                this.RaisePropertyChanged("AutoUpdateKeepServices");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://juis.avm.de/response")]
    public partial class ResponseHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nonceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nonce {
            get {
                return this.nonceField;
            }
            set {
                this.nonceField = value;
                this.RaisePropertyChanged("Nonce");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://juis.avm.de/response")]
    public partial class ResponseUpdateInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseHeader responseHeaderField;
        
        private UpdateInfo updateInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseHeader ResponseHeader {
            get {
                return this.responseHeaderField;
            }
            set {
                this.responseHeaderField = value;
                this.RaisePropertyChanged("ResponseHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public UpdateInfo UpdateInfo {
            get {
                return this.updateInfoField;
            }
            set {
                this.updateInfoField = value;
                this.RaisePropertyChanged("UpdateInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://juis.avm.de/request")]
    public partial class BoxInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int hwField;
        
        private int majorField;
        
        private int minorField;
        
        private int patchField;
        
        private int buildnumberField;
        
        private int buildtypeField;
        
        private string serialField;
        
        private string oEMField;
        
        private string langField;
        
        private string countryField;
        
        private string annexField;
        
        private string[] flagField;
        
        private int updateConfigField;
        
        private string providerField;
        
        private string providerNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int HW {
            get {
                return this.hwField;
            }
            set {
                this.hwField = value;
                this.RaisePropertyChanged("HW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
                this.RaisePropertyChanged("Major");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Minor {
            get {
                return this.minorField;
            }
            set {
                this.minorField = value;
                this.RaisePropertyChanged("Minor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Patch {
            get {
                return this.patchField;
            }
            set {
                this.patchField = value;
                this.RaisePropertyChanged("Patch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Buildnumber {
            get {
                return this.buildnumberField;
            }
            set {
                this.buildnumberField = value;
                this.RaisePropertyChanged("Buildnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Buildtype {
            get {
                return this.buildtypeField;
            }
            set {
                this.buildtypeField = value;
                this.RaisePropertyChanged("Buildtype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
                this.RaisePropertyChanged("Serial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string OEM {
            get {
                return this.oEMField;
            }
            set {
                this.oEMField = value;
                this.RaisePropertyChanged("OEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("Lang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Annex {
            get {
                return this.annexField;
            }
            set {
                this.annexField = value;
                this.RaisePropertyChanged("Annex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Flag", Order=12)]
        public string[] Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int UpdateConfig {
            get {
                return this.updateConfigField;
            }
            set {
                this.updateConfigField = value;
                this.RaisePropertyChanged("UpdateConfig");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
                this.RaisePropertyChanged("Provider");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ProviderName {
            get {
                return this.providerNameField;
            }
            set {
                this.providerNameField = value;
                this.RaisePropertyChanged("ProviderName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://juis.avm.de/request")]
    public partial class RequestHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nonceField;
        
        private string userAgentField;
        
        private bool manualRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nonce {
            get {
                return this.nonceField;
            }
            set {
                this.nonceField = value;
                this.RaisePropertyChanged("Nonce");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserAgent {
            get {
                return this.userAgentField;
            }
            set {
                this.userAgentField = value;
                this.RaisePropertyChanged("UserAgent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool ManualRequest {
            get {
                return this.manualRequestField;
            }
            set {
                this.manualRequestField = value;
                this.RaisePropertyChanged("ManualRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://juis.avm.de/updateinfo", ConfigurationName="JUIS.UpdateInfoService")]
    public interface UpdateInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(JuisCheck.JUIS.JuisSoapExceptionBean), Action="", Name="JuisSoapException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ResponseUpdateInfo")]
        JuisCheck.JUIS.ResponseUpdateInfo BoxFirmwareDowngradeCheck(JuisCheck.JUIS.RequestHeader RequestHeader, JuisCheck.JUIS.BoxInfo BoxInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(JuisCheck.JUIS.JuisSoapExceptionBean), Action="", Name="JuisSoapException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ResponseUpdateInfo")]
        JuisCheck.JUIS.ResponseUpdateInfo SoftwareUpdateCheck(JuisCheck.JUIS.RequestHeader RequestHeader, JuisCheck.JUIS.SoftwareInfo SoftwareInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(JuisCheck.JUIS.JuisSoapExceptionBean), Action="", Name="JuisSoapException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ResponseUpdateInfo")]
        JuisCheck.JUIS.ResponseUpdateInfo BoxFirmwareUpdateCheck(JuisCheck.JUIS.RequestHeader RequestHeader, JuisCheck.JUIS.BoxInfo BoxInfo, JuisCheck.JUIS.BoxInfo BoxInfoMeshMaster);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(JuisCheck.JUIS.JuisSoapExceptionBean), Action="", Name="JuisSoapException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ResponseUpdateInfo")]
        JuisCheck.JUIS.ResponseUpdateInfo DeviceFirmwareUpdateCheck(JuisCheck.JUIS.RequestHeader RequestHeader, JuisCheck.JUIS.BoxInfo BoxInfo, JuisCheck.JUIS.DeviceInfo DeviceInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(JuisCheck.JUIS.JuisSoapExceptionBean), Action="", Name="JuisSoapException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ResponseUpdateInfo")]
        JuisCheck.JUIS.ResponseUpdateInfo BPjMUpdateCheck(JuisCheck.JUIS.RequestHeader RequestHeader, JuisCheck.JUIS.BoxInfo BoxInfo, string BPjMVersion);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://juis.avm.de/request")]
    public partial class SoftwareInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string versionField;
        
        private string langField;
        
        private string osField;
        
        private string serialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("Lang");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OS {
            get {
                return this.osField;
            }
            set {
                this.osField = value;
                this.RaisePropertyChanged("OS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
                this.RaisePropertyChanged("Serial");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://juis.avm.de/request")]
    public partial class DeviceInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int typeField;
        
        private int hwField;
        
        private bool hwFieldSpecified;
        
        private string mHWField;
        
        private string versionField;
        
        private string serialField;
        
        private string langField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int HW {
            get {
                return this.hwField;
            }
            set {
                this.hwField = value;
                this.RaisePropertyChanged("HW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HWSpecified {
            get {
                return this.hwFieldSpecified;
            }
            set {
                this.hwFieldSpecified = value;
                this.RaisePropertyChanged("HWSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MHW {
            get {
                return this.mHWField;
            }
            set {
                this.mHWField = value;
                this.RaisePropertyChanged("MHW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
                this.RaisePropertyChanged("Serial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
                this.RaisePropertyChanged("Lang");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UpdateInfoServiceChannel : JuisCheck.JUIS.UpdateInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateInfoServiceClient : System.ServiceModel.ClientBase<JuisCheck.JUIS.UpdateInfoService>, JuisCheck.JUIS.UpdateInfoService {
        
        public UpdateInfoServiceClient() {
        }
        
        public UpdateInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JuisCheck.JUIS.ResponseUpdateInfo BoxFirmwareDowngradeCheck(JuisCheck.JUIS.RequestHeader RequestHeader, JuisCheck.JUIS.BoxInfo BoxInfo) {
            return base.Channel.BoxFirmwareDowngradeCheck(RequestHeader, BoxInfo);
        }
        
        public JuisCheck.JUIS.ResponseUpdateInfo SoftwareUpdateCheck(JuisCheck.JUIS.RequestHeader RequestHeader, JuisCheck.JUIS.SoftwareInfo SoftwareInfo) {
            return base.Channel.SoftwareUpdateCheck(RequestHeader, SoftwareInfo);
        }
        
        public JuisCheck.JUIS.ResponseUpdateInfo BoxFirmwareUpdateCheck(JuisCheck.JUIS.RequestHeader RequestHeader, JuisCheck.JUIS.BoxInfo BoxInfo, JuisCheck.JUIS.BoxInfo BoxInfoMeshMaster) {
            return base.Channel.BoxFirmwareUpdateCheck(RequestHeader, BoxInfo, BoxInfoMeshMaster);
        }
        
        public JuisCheck.JUIS.ResponseUpdateInfo DeviceFirmwareUpdateCheck(JuisCheck.JUIS.RequestHeader RequestHeader, JuisCheck.JUIS.BoxInfo BoxInfo, JuisCheck.JUIS.DeviceInfo DeviceInfo) {
            return base.Channel.DeviceFirmwareUpdateCheck(RequestHeader, BoxInfo, DeviceInfo);
        }
        
        public JuisCheck.JUIS.ResponseUpdateInfo BPjMUpdateCheck(JuisCheck.JUIS.RequestHeader RequestHeader, JuisCheck.JUIS.BoxInfo BoxInfo, string BPjMVersion) {
            return base.Channel.BPjMUpdateCheck(RequestHeader, BoxInfo, BPjMVersion);
        }
    }
}
